#!/usr/bin/env bash
#
# VPS Deployment Script
# Called by GitHub Actions to deploy to 15.204.91.25
#
# Author: Colin Bitterfield
# Email: colin@bitterfield.com
# Date Created: 2026-01-20
# Date Updated: 2026-01-20
# Version: 1.0.0

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}FusionAuth VPS Deployment${NC}"
echo "================================"
echo ""

# Verify required environment variables from GitHub Secrets
REQUIRED_VARS=(
  "DATABASE_PASSWORD"
  "FUSIONAUTH_ADMIN_EMAIL"
  "FUSIONAUTH_ADMIN_PASSWORD"
  "FUSIONAUTH_API_KEY"
  "ADMIN_CLIENT_SECRET"
  "VENDOR_CLIENT_SECRET"
  "STORE_CLIENT_SECRET"
  "EMPLOYEE_CLIENT_SECRET"
)

for var in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!var:-}" ]; then
    echo -e "${RED}ERROR: Required environment variable $var not set${NC}"
    exit 1
  fi
done

# Create .env file from GitHub Secrets
cat > .env <<EOF
# Generated by GitHub Actions: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# DO NOT EDIT MANUALLY

# Environment
ENVIRONMENT=dev

# PostgreSQL Database Configuration
DATABASE_USER=fusionauth
DATABASE_PASSWORD=${DATABASE_PASSWORD}
DATABASE_NAME=fusionauth
DATABASE_HOST=db
DATABASE_PORT=5432

# FusionAuth Runtime Configuration
FUSIONAUTH_RUNTIME_MODE=production
FUSIONAUTH_SILENT_MODE=true
FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart.json

# FusionAuth Application Secrets
FUSIONAUTH_API_KEY=${FUSIONAUTH_API_KEY}
ADMIN_CLIENT_SECRET=${ADMIN_CLIENT_SECRET}
VENDOR_CLIENT_SECRET=${VENDOR_CLIENT_SECRET}
STORE_CLIENT_SECRET=${STORE_CLIENT_SECRET}
EMPLOYEE_CLIENT_SECRET=${EMPLOYEE_CLIENT_SECRET}

# Admin User
FUSIONAUTH_ADMIN_EMAIL=${FUSIONAUTH_ADMIN_EMAIL}
FUSIONAUTH_ADMIN_PASSWORD=${FUSIONAUTH_ADMIN_PASSWORD}

# Environment-specific URLs
OAUTH_CALLBACK_BASE_URL=https://app-dev.marketexpress.us
FUSIONAUTH_PUBLIC_URL=https://auth-dev.marketexpress.us
EOF

echo "✓ Created .env from GitHub Secrets"

# Copy VPS override file to docker-compose.override.yml
cp docker-compose.override.yml.dev docker-compose.override.yml
echo "✓ Configured VPS environment overrides"

# Backup existing database (if running)
if docker-compose ps | grep fusionauth-db | grep -q Up; then
  echo "Creating database backup..."
  BACKUP_FILE="backup-$(date +%Y%m%d-%H%M%S).sql"
  docker-compose exec -T db pg_dump -U fusionauth fusionauth > "$BACKUP_FILE" || true
  echo "✓ Database backed up to $BACKUP_FILE"
fi

# Pull latest images
echo "Pulling Docker images..."
docker-compose pull

# Deploy with zero-downtime restart
echo "Deploying FusionAuth..."
docker-compose up -d --force-recreate

# Wait for health checks
echo "Waiting for FusionAuth to be healthy..."
for i in {1..30}; do
  if curl --fail --silent --insecure https://localhost:9011/api/status >/dev/null 2>&1; then
    echo -e "${GREEN}✓ FusionAuth is healthy!${NC}"
    break
  fi
  if [ $i -eq 30 ]; then
    echo -e "${RED}ERROR: FusionAuth health check timeout${NC}"
    docker-compose logs --tail=50 fusionauth
    exit 1
  fi
  echo "Waiting... ($i/30)"
  sleep 10
done

# Verify Traefik connectivity (optional check)
if command -v curl &> /dev/null; then
  echo "Verifying Traefik connectivity..."
  if curl --fail --silent https://auth-dev.marketexpress.us/api/status >/dev/null 2>&1; then
    echo -e "${GREEN}✓ Traefik routing verified${NC}"
  else
    echo -e "${YELLOW}WARNING: Traefik routing not verified (may take a few minutes)${NC}"
  fi
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "FusionAuth Dev: https://auth-dev.marketexpress.us"
echo "Application Dev: https://app-dev.marketexpress.us"
echo ""
