#!/usr/bin/env bash
#
# VPS Deployment Script
# Called by GitHub Actions to deploy to 15.204.91.25
#
# Author: Colin Bitterfield
# Email: colin@bitterfield.com
# Date Created: 2026-01-20
# Date Updated: 2026-04-06
# Version: 2.1.0
#
# Changelog:
#   2.1.0: Add FA_TENANT_ID, FA_APP_ID_*, FUSIONAUTH_API_KEY_ID, FA_SMTP_* to .env
#          generation — required for kickstart variable substitution
#   2.0.0: Platform v2 — update REQUIRED_VARS for B2B/B2C/B2G secrets + admin passwords
#   1.0.0: Initial version

set -euo pipefail

# Colors for output
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${GREEN}FusionAuth VPS Deployment${NC}"
echo "================================"
echo ""

# Verify required environment variables from GitHub Secrets
REQUIRED_VARS=(
  "DATABASE_PASSWORD"
  "FUSIONAUTH_ADMIN_EMAIL"
  "FUSIONAUTH_ADMIN_PASSWORD"
  "FUSIONAUTH_API_KEY"
  "FUSIONAUTH_API_KEY_ID"
  "FA_TENANT_ID"
  "FA_APP_ID_ADMIN"
  "FA_APP_ID_VENDOR"
  "FA_APP_ID_B2B"
  "FA_APP_ID_B2C"
  "FA_APP_ID_B2G"
  "ADMIN_CLIENT_SECRET"
  "VENDOR_CLIENT_SECRET"
  "B2B_CLIENT_SECRET"
  "B2C_CLIENT_SECRET"
  "B2G_CLIENT_SECRET"
  "ADMIN_FUSION_PASSWORD"
  "ADMIN_EMPLOYEE_PASSWORD"
  "ADMIN_B2B_PASSWORD"
  "ADMIN_B2G_PASSWORD"
  "ADMIN_B2C_PASSWORD"
  "FA_SMTP_HOST"
  "FA_SMTP_PORT"
  "FA_SMTP_USER"
  "FA_SMTP_PASS"
  "FA_SMTP_FROM_EMAIL"
  "FA_SMTP_FROM_NAME"
)

for var in "${REQUIRED_VARS[@]}"; do
  if [ -z "${!var:-}" ]; then
    echo -e "${RED}ERROR: Required environment variable $var not set${NC}"
    exit 1
  fi
done

# Create .env file from GitHub Secrets
cat > .env <<EOF
# Generated by GitHub Actions: $(date -u +"%Y-%m-%d %H:%M:%S UTC")
# DO NOT EDIT MANUALLY

# Environment
ENVIRONMENT=dev

# PostgreSQL Database Configuration
DATABASE_USER=fusionauth
DATABASE_PASSWORD=${DATABASE_PASSWORD}
DATABASE_NAME=fusionauth
DATABASE_HOST=db
DATABASE_PORT=5432

# FusionAuth Runtime Configuration
FUSIONAUTH_RUNTIME_MODE=production
FUSIONAUTH_SILENT_MODE=true
FUSIONAUTH_APP_KICKSTART_FILE=/usr/local/fusionauth/kickstart/kickstart-dev.json

# FusionAuth Application Secrets
FUSIONAUTH_API_KEY=${FUSIONAUTH_API_KEY}
FUSIONAUTH_API_KEY_ID=${FUSIONAUTH_API_KEY_ID}
ADMIN_CLIENT_SECRET=${ADMIN_CLIENT_SECRET}
VENDOR_CLIENT_SECRET=${VENDOR_CLIENT_SECRET}
B2B_CLIENT_SECRET=${B2B_CLIENT_SECRET}
B2C_CLIENT_SECRET=${B2C_CLIENT_SECRET}
B2G_CLIENT_SECRET=${B2G_CLIENT_SECRET}

# Tenant and Application IDs (must match live instance)
FA_TENANT_ID=${FA_TENANT_ID}
FA_APP_ID_ADMIN=${FA_APP_ID_ADMIN}
FA_APP_ID_VENDOR=${FA_APP_ID_VENDOR}
FA_APP_ID_B2B=${FA_APP_ID_B2B}
FA_APP_ID_B2C=${FA_APP_ID_B2C}
FA_APP_ID_B2G=${FA_APP_ID_B2G}

# Admin User Credentials
FUSIONAUTH_ADMIN_EMAIL=${FUSIONAUTH_ADMIN_EMAIL}
FUSIONAUTH_ADMIN_PASSWORD=${FUSIONAUTH_ADMIN_PASSWORD}
ADMIN_FUSION_PASSWORD=${ADMIN_FUSION_PASSWORD}
ADMIN_EMPLOYEE_PASSWORD=${ADMIN_EMPLOYEE_PASSWORD}
ADMIN_B2B_PASSWORD=${ADMIN_B2B_PASSWORD}
ADMIN_B2G_PASSWORD=${ADMIN_B2G_PASSWORD}
ADMIN_B2C_PASSWORD=${ADMIN_B2C_PASSWORD}

# Mailersend SMTP (for FusionAuth password reset / verification emails)
FA_SMTP_HOST=${FA_SMTP_HOST}
FA_SMTP_PORT=${FA_SMTP_PORT}
FA_SMTP_USER=${FA_SMTP_USER}
FA_SMTP_PASS=${FA_SMTP_PASS}
FA_SMTP_FROM_EMAIL=${FA_SMTP_FROM_EMAIL}
FA_SMTP_FROM_NAME=${FA_SMTP_FROM_NAME}

# Environment-specific URLs
OAUTH_CALLBACK_BASE_URL=https://api.marketexpress.us
FUSIONAUTH_PUBLIC_URL=https://auth.marketexpress.us
EOF

echo "✓ Created .env from GitHub Secrets"

# Generate kickstart-dev.json with dev environment values
echo "Generating kickstart-dev.json..."
bash scripts/generate-kickstart-dev.sh
echo "✓ Generated kickstart-dev.json"

# Copy VPS override file to docker-compose.override.yml
cp docker-compose.override.yml.dev docker-compose.override.yml
echo "✓ Configured VPS environment overrides"

# Backup existing database (if running)
if docker compose ps | grep fusionauth-db | grep -q Up; then
  echo "Creating database backup..."
  BACKUP_FILE="backup-$(date +%Y%m%d-%H%M%S).sql"
  docker compose exec -T db pg_dump -U fusionauth fusionauth > "$BACKUP_FILE" || true
  echo "✓ Database backed up to $BACKUP_FILE"
fi

# Pull latest images
echo "Pulling Docker images..."
docker compose pull

# Clear stale renamed containers before recreating.
#
# `docker compose up --force-recreate` renames the running container to
# <shorthash>_<name> before creating its replacement. If a previous run died
# between those two steps, that renamed container survives and the next deploy
# fails with:
#   Error when allocating new name: Conflict. The container name
#   "/fusionauth-app" is already in use by container "<id>"
# Compose then removes the ORIGINAL container and aborts, leaving FusionAuth
# down. That is what happened on 2026-07-27 — auth was offline until the stale
# container was removed by hand, while Traefik served a maintenance page that
# still returned HTTP 200.
echo "Clearing any stale renamed containers..."
for svc in fusionauth-app fusionauth-db; do
  # matches the <shorthash>_<name> form only, never the live container
  docker ps -a --format '{{.Names}}' \
    | grep -E "^[0-9a-f]{12}_${svc}$" \
    | while read -r stale; do
        echo "  removing stale container: ${stale}"
        docker rm -f "${stale}" >/dev/null 2>&1 || true
      done
done

# NOT zero-downtime: --force-recreate stops and replaces the container. The
# gap is short but real, so the health check below is what makes the deploy
# trustworthy, not the flag.
echo "Deploying FusionAuth..."
if ! docker compose up -d --force-recreate --remove-orphans; then
  echo "compose up failed — retrying once after clearing conflicts"
  docker compose down --remove-orphans || true
  docker compose up -d --remove-orphans
fi

# A failed recreate can leave the service stopped. Fail loudly rather than
# proceeding to a health check that will time out with no explanation.
if ! docker compose ps --status running --services | grep -q fusionauth; then
  echo "ERROR: fusionauth container is not running after deploy"
  docker compose ps
  docker compose logs --tail=50 fusionauth || true
  exit 1
fi

# Wait for health checks
echo "Waiting for FusionAuth to be healthy..."
for i in {1..30}; do
  if curl --fail --silent --insecure https://localhost:9011/api/status >/dev/null 2>&1; then
    echo -e "${GREEN}✓ FusionAuth is healthy!${NC}"
    break
  fi
  if [ $i -eq 30 ]; then
    echo -e "${RED}ERROR: FusionAuth health check timeout${NC}"
    docker compose logs --tail=50 fusionauth
    exit 1
  fi
  echo "Waiting... ($i/30)"
  sleep 10
done

# Verify Traefik connectivity (optional check)
if command -v curl &> /dev/null; then
  echo "Verifying Traefik connectivity..."
  if curl --fail --silent https://auth.marketexpress.us/api/status >/dev/null 2>&1; then
    echo -e "${GREEN}✓ Traefik routing verified${NC}"
  else
    echo -e "${YELLOW}WARNING: Traefik routing not verified (may take a few minutes)${NC}"
  fi
fi

echo ""
echo -e "${GREEN}========================================${NC}"
echo -e "${GREEN}Deployment Complete!${NC}"
echo -e "${GREEN}========================================${NC}"
echo ""
echo "FusionAuth: https://auth.marketexpress.us"
echo "API: https://api.marketexpress.us"
echo ""
